
microserviceviewerbackend:
  cors:
    allowedOrigins: http://localhost:4200, https://localhost:4200
    allowedMethods: GET, POST, PUT, DELETE

spring:
  datasource:
    url: jdbc:mysql://localhost:8889/MicroservicesViewer?serverTimezone=UTC
    username: root
    password: root
  jpa:
    show-sql: true